apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudappdeploy
  labels:
    app: cloudappdeploy
  namespace: namespace-workflow-1716641034975
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudappdeploy
  template:
    metadata:
      labels:
        app: cloudappdeploy
    spec:
      containers:
        - name: cloudappdeploy
          image: acrworkflow1716641034975.azurecr.io/image-workflow-1716641034975:latest
          ports:
            - containerPort: 3000