apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudappdeploy
  labels:
    app: cloudappdeploy
  namespace: prasada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudappdeploy
  template:
    metadata:
      labels:
        app: cloudappdeploy
    spec:
      containers:
        - name: cloudappdeploy
          image: cloudappprasada.azurecr.io/cloudapp:latest
          ports:
            - containerPort: 3000