apiVersion: v1
kind: Service
metadata:
  name: cloudappdeploy
  namespace: prasada
spec:
  type: LoadBalancer
  selector:
    app: cloudappdeploy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000